{
 "title": "[os] xOpenSearch",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "opensearch-prod, opensearch-2-prod, recs-opensearch-prod, recs-2-opensearch-prod"
   }
  ]
 },
 "panels": [
  {
   "title": "opensearch_index_requestcache_memory_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (index) (opensearch_index_requestcache_memory_size_bytes{context=\"total\", namespace=\"$namespace\"}) > 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "opensearch_index_querycache_memory_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (index,pod) (opensearch_index_querycache_memory_size_bytes{context=\"total\", namespace=\"$namespace\", index!~\"\\\\..+\"}) > 0",
     "legendFormat": "{{index}} - {{pod}}"
    }
   ]
  },
  {
   "title": "opensearch_indices_search_query_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod,) (rate(opensearch_indices_search_query_count{namespace=\"$namespace\"}[2m])) > 0\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fs_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(opensearch_fs_io_total_read_bytes{namespace=\"$namespace\"}[2m]) > 0",
     "legendFormat": "read - {{pod}}"
    },
    {
     "expr": "- rate(opensearch_fs_io_total_write_bytes{namespace=\"$namespace\"}[2m]) < 0",
     "legendFormat": "write - {{pod}}"
    }
   ]
  },
  {
   "title": "iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(opensearch_fs_io_total_operations{namespace=\"$namespace\"}[2m]) > 0",
     "legendFormat": "read - {{pod}}"
    }
   ]
  },
  {
   "title": "opensearch_indices_indexing_index_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(opensearch_indices_indexing_index_count{namespace=\"$namespace\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "opensearch_threadpool_tasks_number",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (pod, name) (opensearch_threadpool_tasks_number{namespace=\"$namespace\"}) > 0\n",
     "legendFormat": "{{name}} - {{ pod }}"
    }
   ]
  },
  {
   "title": "opensearch_index_search_open_contexts_number",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "sum by (index) (opensearch_index_search_open_contexts_number{context=\"total\", namespace=\"$namespace\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "opensearch_os_cpu_percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opensearch_os_cpu_percent{namespace=\"$namespace\"} #opensearch_process_cpu_percent",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "opensearch_jvm_gc_collection_time_seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 21 },
   "targets": [
    {
     "expr": "sum(irate(opensearch_jvm_gc_collection_time_seconds{namespace=\"$namespace\"}[2m]))",
     "legendFormat": "{{name}} - {{ pod }}"
    }
   ]
  },
  {
   "title": "opensearch_indices_store_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_indices_store_size_bytes{namespace=\"$namespace\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}