{
 "title": "Capacity Planning",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(up{job=\"node-exporter\"}, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{}, namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Requested CPU",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\"}[5m])* on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})) / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}[5m])))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "% Requested Memory",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\"}[5m])* on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})) / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}[5m])))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "% Actual CPU Usage",
     "type": "gauge",
     "description": "How much CPU is actually used in the cluster (CPU usage / Allocatable CPU).",
     "gridPos": { "h": 8, "w": 3, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (node) (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m])))\n / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}[5m])))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "% Actual Memory Usage",
     "type": "gauge",
     "description": "How much memory is actually used in the cluster (Memory usage / Allocatable Memory).",
     "gridPos": { "h": 8, "w": 3, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (node) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\"})) / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}[5m])))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "% Used Requested CPU",
     "type": "gauge",
     "description": "How many requested cores are used (Actual CPU / Requested CPU).",
     "gridPos": { "h": 8, "w": 3, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (node) (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m]))) / sum(sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\"}[5m])))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "% Used Requested Memory",
     "type": "gauge",
     "description": "How much requested memory is used (Actual Memory / Requested Memory). ",
     "gridPos": { "h": 8, "w": 3, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (node) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\"} )) / sum(sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "% Pods Usage",
     "type": "gauge",
     "description": "Pods number in the cluster / Allocatable Pods.",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(((max by (pod, namespace)(kube_pod_container_status_running))==1) * on (pod, namespace) group_right() (kube_pod_info{}==1) \n) / sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\"}[5m])))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Allocatable / Requested / Unused",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Allocatable CPU",
   "type": "timeseries",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}[5m]))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}[5m])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Unrequested CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\"}[5m])) - on(node) (sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\"}[5m])* on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"}))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"cpu\"}[5m])) - on(node) (sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\"}[5m])* on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Unused Requested CPU (Idle)",
   "type": "timeseries",
   "description": "Difference between requested cores and used cores.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m]) - on (namespace,pod,container,node) group_left avg by (namespace,pod,container, node)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 > 0\n",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m]) - on (namespace,pod,container,node) group_left avg by (namespace,pod,container, node)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 > 0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "timeseries",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}[5m]))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}[5m])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Unrequested Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\"}[5m])) - on(node) (sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\"}[5m])* on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"}))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"memory\"}[5m])) - on(node) (sum by (node) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\"}[5m])* on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Unused Requested Memory",
   "type": "timeseries",
   "description": "Difference between requested memory and used memory.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(sum by (node) (container_memory_working_set_bytes:without_kmem{container!=\"POD\",container!=\"\"} ) - sum by (node) (kube_pod_container_resource_requests{resource=\"memory\"})) * -1 > 0\n",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum((sum by (node) (container_memory_working_set_bytes:without_kmem{container!=\"POD\",container!=\"\"} ) - sum by (node) (kube_pod_container_resource_requests{resource=\"memory\"})) * -1 > 0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Allocatable Pods",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\"}[5m]))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\"}[5m])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Available Pod slots",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\"}[5m])) - on(node) (count by (node) (\n  ((max by (pod, namespace)(kube_pod_container_status_running))==1) * on (pod, namespace) group_right() (kube_pod_info{}==1) \n))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(sum by (node) (avg_over_time(kube_node_status_allocatable{resource=\"pods\"}[5m])) - on(node) (count by (node) (\n  ((max by (pod, namespace)(kube_pod_container_status_running))==1) * on (pod, namespace) group_right() (kube_pod_info{}==1) \n)))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Top 10 CPU overrequested containers",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(10, (sum by (namespace,pod,container)((rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container!=\"POD\",container!=\"\"}[$__rate_interval])) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"}))) * -1 > 0)\n"
    }
   ]
  },
  {
   "title": "Top 10 Memory overrequested containers",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "topk(50, (sum by (namespace,container,pod) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\"}) - on (namespace,pod,container) avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\"})) * -1 >0)\n"
    }
   ]
  },
  {
   "title": "Top 10 CPU underrequested containers",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "topk(10, (sum by (namespace,pod,container)((rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container!=\"POD\",container!=\"\"}[2m])) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"}))) > 0)\n"
    }
   ]
  },
  {
   "title": "Top 10 Memory underrequested containers",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "topk(10, (sum by (namespace,container,pod) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\",namespace=~\"$namespace\"}) - on (namespace,pod,container) avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\",namespace=~\"$namespace\"})) >0)\n"
    }
   ]
  }
 ]
}