{
 "title": "k8s pods",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pods cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, pod)\n(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"\"}[2m])) > 0.02\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "node idle cores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throttling > 1%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(\n    sum by (namespace, pod) (rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\", namespace!=\"kube-system\"}[2m])) \n    / \n    sum by (namespace, pod) (rate(container_cpu_cfs_periods_total{namespace=~\"$namespace\"}[2m]))) \n    *\n    sum by (namespace,pod) (kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"cpu\",unit=\"core\"}\n) > 0.01",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "node_filesystem_avail_bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device!=\"shm\", mountpoint!~\"/run.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) \n(container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "[total on nodes]"
    }
   ]
  },
  {
   "title": "nodes memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes) - (node_memory_MemFree_bytes) - (node_memory_Buffers_bytes) - (node_memory_Cached_bytes)",
     "legendFormat": "used - {{instance}}"
    },
    { "expr": "(node_memory_MemTotal_bytes)", "legendFormat": "total on each" }
   ]
  },
  {
   "title": "iops",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(container_fs_reads_total{namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}[2m])) > 0",
     "legendFormat": "read - {{pod}}"
    },
    {
     "expr": "- sum by (namespace, pod) (rate(container_fs_writes_total{namespace=~\"$namespace\", container!=\"POD\", container!=\"\"}[2m])) < 0",
     "legendFormat": "write - {{pod}}"
    },
    { "expr": "0", "legendFormat": "0" }
   ]
  },
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod) (rate(container_network_receive_bytes_total{namespace=~\"$namespace\", namespace!=\"kube-system\", pod!~\".*node-exporter.+\"}[2m])) > 1000",
     "legendFormat": "rx - {{pod}}"
    },
    {
     "expr": "- sum by (namespace,pod) (rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", namespace!=\"kube-system\", pod!~\".*node-exporter.+\"}[2m])) < 1000",
     "legendFormat": "tx - {{pod}}"
    }
   ]
  }
 ]
}